### ISSUE TITLE
Map: County colors

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/GIS-Resources-Map#8]
Color county white/transparent/no fill if no contact name exists, keep current color for counties with data

**Comment by xta** [comment]
What county `fillColor` do we want on page load? For those without data, change it to white? For those with data, keep it as is (a light gray color)?

Also, this issue doesn't touch upon the mouseOver/hover of county areas, right?

Thanks

**Comment by chanbot5000** [comment]
County Colors:
No Info: color white/transparent
Info: leave light blue

thx rex
